# Generated by Django 5.2.4 on 2025-07-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.AddField(
            model_name='content',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AddField(
            model_name='content',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('prac', 'Practical'), ('note', 'Notes'), ('ass', 'Assignment'), ('project', 'Project')], max_length=10),
        ),
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='content',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='content',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=2),
        ),
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.CharField(help_text='Comma-separated (3–5 tags)', max_length=200),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['content_type', 'date'], name='content_con_content_6f966c_idx'),
        ),
    ]
